services:
  - type: web
    name: regression-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    repo: https://github.com/Parthsawant1298/object-detection-project-1754972259.git
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: MODEL_FILE
        value: best_model.pt
      - key: PORT
        value: "10000"
